fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - 192.168.2.137:22122
upload:
  base-url: http://192.168.2.137/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif